### PR TITLE
UC 17- Report - All Capital Cities in the world

### PR DESCRIPTION
**Pull request by mikemmanuel**
Kindly review please. Test & Screenshot will be pushed later.

### CODE REVIEW

**Comment by BobbyWal78** [comment]
ScreenShot Missing from the Readme file., and if requiement has been met

**Comment by BobbyWal78** [comment]
integeration testing not seen .

**Comment by mikemmanuel** [comment]
Changes made and conflicts resolved. Kindly review.

**Comment by mikemmanuel** [comment]
Read me is updated in Pull req #116

**Review by BobbyWal78 — APPROVED** [review]
Updates approved.

**Pull request merged**
